### ISSUE TITLE
manager fails to run in hack/setup-local-multi-cluster.sh setup

### ISSUE THREAD

**Issue by revit13** [fybrik/fybrik#718]
manager fails with CrashLoopBackOff when running hack/setup-local-multi-cluster.sh script.

This is the manager log in kind-control cluster:

` (⎈ |kind-control:m4d-system) (master)]$ k logs manager-bcc9bcb74-wdqnb  manager 
2021-07-19T06:01:11.571Z        INFO    setup   creating manager
2021-07-19T06:01:12.477Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": "127.0.0.1:8080"}
2021-07-19T06:01:12.477Z        INFO    setup   creating cluster manager
2021-07-19T06:01:12.477Z        INFO    setup   Using razee local at http://razeedash-api-lb.razee.svc.cluster.local:8081
2021-07-19T06:01:14.047Z        ERROR   setup   unable to initialize cluster manager    {"error": "invalid character '<' looking for 
beginning of value"}
main.run
        /home/eres/the-mesh-for-data/manager/main.go:75
main.main
        /home/eres/the-mesh-for-data/manager/main.go:200
runtime.main
        /usr/local/go/src/runtime/proc.go:225`

**Comment by pugangxa** [comment]
This should be fixed by PR #1081

**Comment by roytman** [comment]
@revit13 , I see that PR #1081 is merged, can we close the issue?

**Comment by roytman** [comment]
@revit13  can you validate that PR #1081 fixed the issue, and close it.

**Comment by revit13** [comment]
@pugangxa I see that the manager still fails with CrashLoopBackOff when running `./hack/setup-local-multi-cluster.sh` with the following message:

```
{"level":"error","Setup":"main","error":"No user found with this login credentials.","time":"2022-07-24T09:33:32Z","caller":"/data/the-mesh-for-data/manager/main.go:110","message":"unable to initialize cluster manager"}`

**Comment by pugangxa** [comment]
I think the original issue reported is gone, this seems a new issue according to the message, maybe caused by some changes these days. I can take a look when I have time, maybe some time later though.
